language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - extra-google-google_play_services
  licenses:
    - '.+'
before_script:
    - wget -O libs/libwebrtc-m81.aar http://gultsch.de/files/libwebrtc-m81.aar
script:
    - ./gradlew assembleConversationsFreeSystemRelease
    - ./gradlew assembleQuicksyFreeCompatRelease

before_install:
    - yes | sdkmanager "platforms;android-28"
