on:
  push:

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/redemonbr/android-sdk:node-lts-api-30
      env:
        ASDK_PROMPT_LICENSES: yes
        ASDK_ACCEPT_LICENSES_SILENT: yes
        ASDK_ACCEPT_LICENSES: yes

    steps:
      - uses: https://git.fucktheforce.de/actions/checkout@v4
      - name: build debug apk
        run: |
          cd $GITHUB_WORKSPACE
          ./gradlew assembleMonoclesPiratxDebug --no-daemon
