on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/redemonbr/android-sdk:node-lts-api-30

    steps:
      - name: accept licenses
        run: yes | sdkmanager --licenses > /dev/null
      - uses: https://git.fucktheforce.de/actions/checkout@v4
      - name: build debug apk
        run: |
          cd $GITHUB_WORKSPACE
          ./gradlew assembleMonoclesPiratxDebug -Dorg.gradle.jvmargs=-Xmx2g --no-daemon
      - uses: https://git.fucktheforce.de/actions/upload-artifact@v3
        with:
          name: debug-apks
          path: ${{ github.workspace }}/build/outputs/apk/*/debug/*.apk
          if-no-files-found: error
          retention-days: 10

